export const Global = {
    noticeContentLabel: null,
    isLogin:false,
    publickey:'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbVOyn+Ha8q4UR3R5d3Ka3PIQswciB6EeieGdeksHTdZB2u7Q7ao/W32TQ0jvjU6i5CwiTdo3eDs+SdxxkM1EbljtQk9gWMmRZebUxqDCu0RnLP5tASxerS2XoRVQvSNXj1K/fncB1b1eFZv4Kqq3IEllTfBsfcx65xqV4Ur/2SwIDAQAB',
    ip:'0.0.0.0',
    area:'未知',
    socketObj:null,
    rType:'',
    bgSound:true,
    bgMusic:false,
     serverUrl: 'https://pc2.th371.com/',
    serverHost:'pc2.th371.com',
    //serverUrl: 'http://test.hjkf88.com/',
    //serverHost:'test.hjkf88.com',
    noticePm:'',
    testLogin:600,
    roomList:[] ,
    roomId:'',
}